on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"

name: 1. Dev Build & Deploy
run-name: Dev Build & Deploy

jobs:
  build_and_deploy:
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-rayhead-container.yaml@ray-docker-build
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
      ARTIFACTORY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_TOKEN }}
    with:
      ARTIFACTORY_REGISTRY: "p6m.jfrog.io"
      APPS: {{ project-name }} 
      DOCKER_REPO: {{ org-solution-name }}-docker/application